# Generated by Django 4.2.29 on 2026-03-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0002_dispatchguide_dispatchguideitem"),
        ("crm", "0001_initial"),
        ("accounting", "0003_pettycash_pettycashtransaction_accountreceivable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Numero"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En Proceso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Fecha Programada")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Inicio"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Picking",
                "verbose_name_plural": "Ordenes de Picking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Numero"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmado"),
                            ("in_process", "En Preparacion"),
                            ("ready", "Listo para Despacho"),
                            ("dispatched", "Despachado"),
                            ("delivered", "Entregado"),
                            ("invoiced", "Facturado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Fecha de Pedido")),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Esperada de Entrega"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Real de Entrega"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Direccion de Entrega"),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Condiciones de Pago"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas Internas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="crm.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "dispatch_guide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="logistics.dispatchguide",
                        verbose_name="Guia de Remision",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="accounting.invoice",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="logistics.warehouse",
                        verbose_name="Almacen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Venta",
                "verbose_name_plural": "Pedidos de Venta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Numero"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contacto"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefono"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("sent", "Enviada"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                            ("expired", "Expirada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de Emision")),
                ("valid_until", models.DateField(verbose_name="Valida Hasta")),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        default="Contado",
                        max_length=200,
                        verbose_name="Condiciones de Pago",
                    ),
                ),
                (
                    "delivery_terms",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Condiciones de Entrega",
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tiempo de Entrega"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Descuento",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas Internas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="crm.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation",
                        to="sales.salesorder",
                        verbose_name="Pedido Generado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotizacion",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesQuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripcion"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "affectation_type",
                    models.CharField(
                        default="10", max_length=2, verbose_name="Tipo Afectacion"
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_items",
                        to="logistics.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesquotation",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.unitofmeasure",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cotizacion",
                "verbose_name_plural": "Items de Cotizacion",
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripcion"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "delivered_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Cantidad Entregada",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "affectation_type",
                    models.CharField(
                        default="10", max_length=2, verbose_name="Tipo Afectacion"
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_items",
                        to="logistics.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.unitofmeasure",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Items de Pedido",
            },
        ),
        migrations.CreateModel(
            name="PickingOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Cantidad Solicitada",
                    ),
                ),
                (
                    "quantity_picked",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Cantidad Preparada",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ubicacion en Almacen"
                    ),
                ),
                (
                    "picked",
                    models.BooleanField(default=False, verbose_name="Preparado"),
                ),
                ("picked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Observacion"
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_picked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "picking_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.pickingorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_items",
                        to="logistics.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Picking",
                "verbose_name_plural": "Items de Picking",
            },
        ),
        migrations.AddField(
            model_name="pickingorder",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picking_orders",
                to="sales.salesorder",
                verbose_name="Pedido de Venta",
            ),
        ),
        migrations.AddField(
            model_name="pickingorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="picking_orders",
                to="logistics.warehouse",
                verbose_name="Almacen",
            ),
        ),
    ]
