# Generated by Django 4.2.29 on 2026-03-09 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0002_dispatchguide_dispatchguideitem"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Codigo"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_immediate",
                    models.BooleanField(default=False, verbose_name="Pago Inmediato"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Termino de Pago",
                "verbose_name_plural": "Terminos de Pago",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Codigo"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dolares (USD)")],
                        default="PEN",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Por Defecto"),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente Desde"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente Hasta"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lista de Precios",
                "verbose_name_plural": "Listas de Precios",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="salesquotation",
            name="signature",
            field=models.TextField(blank=True, verbose_name="Firma del Cliente"),
        ),
        migrations.AddField(
            model_name="salesquotation",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Firma"
            ),
        ),
        migrations.AddField(
            model_name="salesquotation",
            name="signed_by",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Firmado por"
            ),
        ),
        migrations.CreateModel(
            name="SalesActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Cambio de Estado"),
                            ("note", "Nota"),
                            ("signature", "Firma"),
                            ("email", "Email Enviado"),
                            ("document", "Documento"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titulo")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Valor Nuevo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sales.salesorder",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sales.salesquotation",
                        verbose_name="Cotizacion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="sales.paymentterm",
                verbose_name="Termino de Pago",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="sales.pricelist",
                verbose_name="Lista de Precios",
            ),
        ),
        migrations.AddField(
            model_name="salesquotation",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="sales.paymentterm",
                verbose_name="Termino de Pago",
            ),
        ),
        migrations.AddField(
            model_name="salesquotation",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="sales.pricelist",
                verbose_name="Lista de Precios",
            ),
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="Cantidad Minima",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.pricelist",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_items",
                        to="logistics.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Lista de Precios",
                "verbose_name_plural": "Items de Lista de Precios",
                "ordering": ["product__name", "min_quantity"],
                "unique_together": {("price_list", "product", "min_quantity")},
            },
        ),
        migrations.CreateModel(
            name="PaymentTermInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=1, verbose_name="Secuencia"),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
                ("days", models.PositiveIntegerField(verbose_name="Dias")),
                (
                    "payment_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="sales.paymentterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota de Pago",
                "verbose_name_plural": "Cuotas de Pago",
                "ordering": ["sequence"],
                "unique_together": {("payment_term", "sequence")},
            },
        ),
    ]
