# Generated by Django 4.2.29 on 2026-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=80, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Habilitado"),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("all", "Todos los entornos"),
                            ("testing", "Solo Testing"),
                            ("production", "Solo Producción"),
                        ],
                        default="testing",
                        max_length=20,
                        verbose_name="Entorno",
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=50, verbose_name="Módulo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["module", "code"],
            },
        ),
    ]
