# Generated by Django 4.2.29 on 2026-03-09 19:38

from django.db import migrations


FEATURE_FLAGS = [
    # CRITICAL - Facturacion Electronica
    {
        'code': 'sunat_digital_signature',
        'name': 'Firma Digital XML (xmlsec)',
        'description': 'Firma digital de comprobantes XML usando certificado digital .pfx/.p12. Requerido para envio a SUNAT produccion.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'sunat_qr_code',
        'name': 'Generacion QR en Comprobantes',
        'description': 'Genera codigo QR con datos del comprobante (RUC, tipo, serie, IGV, total, hash). Requerido para impresion.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'invoice_pdf_generation',
        'name': 'Generacion PDF de Comprobantes',
        'description': 'Genera PDF A4 y ticket de facturas, boletas, notas de credito/debito usando ReportLab.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'accounting',
    },
    {
        'code': 'sunat_nota_credito_debito',
        'name': 'XML Nota Credito/Debito (07/08)',
        'description': 'Genera XML UBL 2.1 correcto para Notas de Credito y Debito con BillingReference y DiscrepancyResponse.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'sunat_response_parsing',
        'name': 'Parsing Respuesta SUNAT + CDR',
        'description': 'Parsea respuesta SOAP de SUNAT, extrae codigos de error, guarda archivo CDR (Constancia de Recepcion).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'invoice_amount_in_words',
        'name': 'Monto en Letras',
        'description': 'Convierte automaticamente el total del comprobante a texto en espanol (SON: CIEN CON 00/100 SOLES).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'accounting',
    },
    # HIGH PRIORITY
    {
        'code': 'sunat_resumen_diario',
        'name': 'Resumen Diario de Boletas',
        'description': 'Genera XML de Resumen Diario y lo envia a SUNAT. Requerido para boletas de venta.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'sunat_comunicacion_baja',
        'name': 'Comunicacion de Baja',
        'description': 'Genera XML de Comunicacion de Baja para anular comprobantes ante SUNAT.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'sunat_gre',
        'name': 'Guia Remision Electronica (GRE)',
        'description': 'Genera XML de Guia de Remision y lo envia via API REST de SUNAT (GRE 2.0).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'invoice_auto_send_sunat',
        'name': 'Auto-envio a SUNAT',
        'description': 'Envia automaticamente el comprobante a SUNAT al emitirlo (async via Celery).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    # MEDIUM
    {
        'code': 'sunat_ruc_autofill',
        'name': 'Auto-llenado por RUC',
        'description': 'Consulta SUNAT al ingresar RUC y auto-rellena datos del cliente (razon social, direccion).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'crm',
    },
    {
        'code': 'invoice_series_validation',
        'name': 'Validacion Series SUNAT',
        'description': 'Valida formato de series (F001 para facturas, B001 para boletas, FC01 para NC, FD01 para ND).',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'accounting',
    },
    {
        'code': 'sunat_sire_export',
        'name': 'Exportacion SIRE',
        'description': 'Exporta Registro de Ventas y Compras en formato SIRE para declaracion mensual.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'sunat',
    },
    {
        'code': 'invoice_batch_processing',
        'name': 'Procesamiento Batch de Comprobantes',
        'description': 'Permite seleccionar multiples comprobantes para envio masivo a SUNAT.',
        'is_enabled': False,
        'environment': 'testing',
        'module': 'accounting',
    },
]


def seed_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    for flag_data in FEATURE_FLAGS:
        FeatureFlag.objects.update_or_create(
            code=flag_data['code'],
            defaults=flag_data,
        )


def remove_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    codes = [f['code'] for f in FEATURE_FLAGS]
    FeatureFlag.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_feature_flag_model"),
    ]

    operations = [
        migrations.RunPython(seed_flags, remove_flags),
    ]
