# Generated by Django 4.2.29 on 2026-03-08 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, verbose_name="Nro. Factura Proveedor"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Fecha de Factura")),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Parcialmente Pagado"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cuenta por Pagar",
                "verbose_name_plural": "Cuentas por Pagar",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("01", "Factura"),
                            ("03", "Boleta de Venta"),
                            ("07", "Nota de Crédito"),
                            ("08", "Nota de Débito"),
                        ],
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                ("series", models.CharField(max_length=4, verbose_name="Serie")),
                (
                    "next_correlative",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Siguiente Correlativo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Serie de Documento",
                "verbose_name_plural": "Series de Documentos",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("01", "Factura"),
                            ("03", "Boleta de Venta"),
                            ("07", "Nota de Crédito"),
                            ("08", "Nota de Débito"),
                        ],
                        max_length=2,
                        verbose_name="Tipo Comprobante",
                    ),
                ),
                ("series", models.CharField(max_length=4, verbose_name="Serie")),
                (
                    "correlative",
                    models.PositiveIntegerField(verbose_name="Correlativo"),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=10,
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "payment_condition",
                    models.CharField(
                        choices=[("cash", "Contado"), ("credit", "Crédito")],
                        default="cash",
                        max_length=10,
                        verbose_name="Condición de Pago",
                    ),
                ),
                ("related_doc_type", models.CharField(blank=True, max_length=2)),
                ("related_series", models.CharField(blank=True, max_length=4)),
                (
                    "related_correlative",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_reason", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "op_gravada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Op. Gravada",
                    ),
                ),
                (
                    "op_exonerada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Op. Exonerada",
                    ),
                ),
                (
                    "op_inafecta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Op. Inafecta",
                    ),
                ),
                (
                    "op_gratuita",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Op. Gratuita",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento Total",
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "amount_in_words",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Monto en Letras"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitida"),
                            ("sent", "Enviada a SUNAT"),
                            ("accepted", "Aceptada por SUNAT"),
                            ("rejected", "Rechazada por SUNAT"),
                            ("cancelled", "Anulada"),
                            ("voided", "Comunicación de Baja"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sunat_response_code", models.CharField(blank=True, max_length=10)),
                ("sunat_response_description", models.TextField(blank=True)),
                ("sunat_ticket", models.CharField(blank=True, max_length=100)),
                ("hash_code", models.CharField(blank=True, max_length=100)),
                ("qr_code", models.TextField(blank=True)),
                (
                    "xml_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/xml/"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/pdf/"),
                ),
                (
                    "cdr_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/cdr/"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "affectation_type",
                    models.CharField(
                        default="10", max_length=2, verbose_name="Tipo Afectación"
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Comprobante",
                "verbose_name_plural": "Ítems de Comprobante",
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Fecha de Pago")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia Bancaria"),
                            ("card", "Tarjeta"),
                            ("check", "Cheque"),
                            ("yape", "Yape"),
                            ("plin", "Plin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounting.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Pago",
                "verbose_name_plural": "Registros de Pago",
                "ordering": ["-payment_date"],
            },
        ),
    ]
