# Generated by Django 4.2.29 on 2026-03-08 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PettyCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "initial_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Inicial"
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Actual"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierta"), ("closed", "Cerrada")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Apertura"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Cierre"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cashes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja Chica",
                "verbose_name_plural": "Cajas Chicas",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Gasto")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office", "Material de Oficina"),
                            ("transport", "Transporte"),
                            ("food", "Alimentacion"),
                            ("maintenance", "Mantenimiento"),
                            ("services", "Servicios"),
                            ("other", "Otros"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripcion"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nro. Comprobante"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="petty_cash/",
                        verbose_name="Archivo",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "petty_cash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.pettycash",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Caja Chica",
                "verbose_name_plural": "Movimientos Caja Chica",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripcion"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Cobrado",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de Emision")),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Parcialmente Cobrado"),
                            ("collected", "Cobrado"),
                            ("overdue", "Vencido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivables_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="crm.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivables",
                        to="accounting.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta por Cobrar",
                "verbose_name_plural": "Cuentas por Cobrar",
                "ordering": ["due_date"],
            },
        ),
    ]
