# Generated by Django 4.2.29 on 2026-03-08 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("accounting", "0003_pettycash_pettycashtransaction_accountreceivable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("remitente", "Remitente"),
                            ("transportista", "Transportista"),
                        ],
                        default="remitente",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("series", models.CharField(max_length=4, verbose_name="Serie")),
                (
                    "correlative",
                    models.PositiveIntegerField(verbose_name="Correlativo"),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de Emision")),
                (
                    "transfer_start_date",
                    models.DateField(verbose_name="Fecha Inicio Traslado"),
                ),
                (
                    "transfer_reason",
                    models.CharField(
                        choices=[
                            ("sale", "Venta"),
                            ("purchase", "Compra"),
                            ("transfer", "Traslado entre establecimientos"),
                            ("consignment", "Consignacion"),
                            ("return", "Devolucion"),
                            ("other", "Otros"),
                        ],
                        max_length=20,
                        verbose_name="Motivo de Traslado",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Descripcion"
                    ),
                ),
                (
                    "origin_address",
                    models.TextField(verbose_name="Direccion de Origen"),
                ),
                (
                    "origin_ubigeo",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Ubigeo Origen"
                    ),
                ),
                (
                    "destination_address",
                    models.TextField(verbose_name="Direccion de Destino"),
                ),
                (
                    "destination_ubigeo",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Ubigeo Destino"
                    ),
                ),
                (
                    "carrier_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Transportista"
                    ),
                ),
                (
                    "carrier_ruc",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="RUC Transportista"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Conductor"
                    ),
                ),
                (
                    "driver_license",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Licencia"
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(blank=True, max_length=10, verbose_name="Placa"),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Peso Bruto (kg)",
                    ),
                ),
                (
                    "packages",
                    models.PositiveIntegerField(default=1, verbose_name="Bultos"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitida"),
                            ("in_transit", "En Transito"),
                            ("delivered", "Entregada"),
                            ("cancelled", "Anulada"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_guides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_guides",
                        to="crm.customer",
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_guides",
                        to="accounting.invoice",
                        verbose_name="Comprobante Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guia de Remision",
                "verbose_name_plural": "Guias de Remision",
                "ordering": ["-created_at"],
                "unique_together": {("series", "correlative")},
            },
        ),
        migrations.CreateModel(
            name="DispatchGuideItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripcion"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="logistics.dispatchguide",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_items",
                        to="logistics.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Guia de Remision",
                "verbose_name_plural": "Items Guia de Remision",
            },
        ),
    ]
