# Generated by Django 4.2.29 on 2026-03-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0002_dispatchguide_dispatchguideitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "bom_type",
                    models.CharField(
                        choices=[
                            ("manufacturing", "Fabricacion"),
                            ("assembly", "Ensamblaje"),
                            ("kit", "Kit"),
                        ],
                        default="manufacturing",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="Cantidad a Producir",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo Estimado",
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo Estimado (min)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lista de Materiales",
                "verbose_name_plural": "Listas de Materiales",
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="BOMComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Componente BOM",
                "verbose_name_plural": "Componentes BOM",
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Numero"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Cantidad a Producir",
                    ),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Cantidad Producida",
                    ),
                ),
                (
                    "quantity_rejected",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Cantidad Rechazada",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmada"),
                            ("in_production", "En Produccion"),
                            ("quality_check", "Control de Calidad"),
                            ("completed", "Terminada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="Fecha Planificada")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo Estimado",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo Real",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="manufacturing.billofmaterials",
                        verbose_name="Lista de Materiales",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="logistics.product",
                        verbose_name="Producto a Fabricar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Produccion",
                "verbose_name_plural": "Ordenes de Produccion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrderComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Cantidad Requerida",
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Cantidad Consumida",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Disponible"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_consumptions",
                        to="logistics.product",
                        verbose_name="Componente",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="manufacturing.productionorder",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.unitofmeasure",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de Produccion",
                "verbose_name_plural": "Componentes de Produccion",
            },
        ),
    ]
