# Generated by Django 4.2.29 on 2026-03-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manufacturing", "0001_initial"),
        ("logistics", "0002_dispatchguide_dispatchguideitem"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="sales.salesorder",
                verbose_name="Pedido de Venta",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_orders",
                to="logistics.warehouse",
                verbose_name="Almacen",
            ),
        ),
        migrations.AddField(
            model_name="bomcomponent",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="bomcomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_boms",
                to="logistics.product",
                verbose_name="Componente",
            ),
        ),
        migrations.AddField(
            model_name="bomcomponent",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.unitofmeasure",
                verbose_name="Unidad",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boms_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="logistics.product",
                verbose_name="Producto Final",
            ),
        ),
    ]
