# Generated by Django 4.2.29 on 2026-03-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Persona Natural"),
                            ("business", "Persona Jurídica"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("RUC", "RUC"),
                            ("CE", "Carné de Extranjería"),
                            ("PAS", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=3,
                        verbose_name="Tipo Doc.",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nro. Documento"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=300, verbose_name="Nombre / Razón Social"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Nombre Comercial"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                ("ubigeo", models.CharField(blank=True, max_length=6)),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provincia"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Distrito"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "credit_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Días de Crédito"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Etiquetas"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("RUC", "RUC"), ("DNI", "DNI")],
                        default="RUC",
                        max_length=3,
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nro. Documento"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Razón Social")),
                ("trade_name", models.CharField(blank=True, max_length=300)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contacto"
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Plazo de Pago (días)"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nro. Cuenta"
                    ),
                ),
                (
                    "bank_cci",
                    models.CharField(blank=True, max_length=50, verbose_name="CCI"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospección"),
                            ("qualification", "Calificación"),
                            ("proposal", "Propuesta"),
                            ("negotiation", "Negociación"),
                            ("closed_won", "Ganada"),
                            ("closed_lost", "Perdida"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Esperado",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Probabilidad (%)"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Esperada de Cierre"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Fuente"),
                ),
                (
                    "lost_reason",
                    models.TextField(blank=True, verbose_name="Motivo de Pérdida"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidad",
                "verbose_name_plural": "Oportunidades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Llamada"),
                            ("email", "Correo"),
                            ("meeting", "Reunión"),
                            ("visit", "Visita"),
                            ("whatsapp", "WhatsApp"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Asunto")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("date", models.DateTimeField(verbose_name="Fecha")),
                (
                    "next_action",
                    models.TextField(blank=True, verbose_name="Próxima Acción"),
                ),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.customer",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="crm.opportunity",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción",
                "verbose_name_plural": "Interacciones",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contacto Principal"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
            },
        ),
    ]
