#!/bin/bash
#
# ERP System - Railway Deploy Guide
# This script guides you through deploying on Railway.app
#
set -euo pipefail

echo "============================================"
echo "  ERP System - Railway Deployment"
echo "============================================"
echo ""
echo "PASO 1: Instalar Railway CLI"
echo "  npm install -g @railway/cli"
echo "  railway login"
echo ""
echo "PASO 2: Crear proyecto"
echo "  railway init"
echo ""
echo "PASO 3: Crear servicios (ejecutar cada uno)"
echo ""
echo "  # Base de datos PRODUCCIÓN"
echo "  railway add --plugin postgresql"
echo "  # En dashboard: renombrar a 'db-production'"
echo ""
echo "  # Base de datos TESTING"
echo "  railway add --plugin postgresql"
echo "  # En dashboard: renombrar a 'db-testing'"
echo ""
echo "  # Redis"
echo "  railway add --plugin redis"
echo ""
echo "PASO 4: Configurar variables de entorno"
echo "  railway variables set SECRET_KEY=\$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')"
echo "  railway variables set DJANGO_SETTINGS_MODULE=erp_system.settings_production"
echo "  railway variables set ALLOWED_HOSTS=tu-app.railway.app,tudominio.com"
echo "  railway variables set COMPANY_NAME='Tu Empresa SAC'"
echo "  railway variables set COMPANY_RUC=20XXXXXXXXX"
echo "  railway variables set SUNAT_PRODUCTION=False"
echo "  railway variables set ENVIRONMENT=production"
echo ""
echo "PASO 5: Deploy"
echo "  railway up"
echo ""
echo "PASO 6: Migrar y crear admin"
echo "  railway run python manage.py migrate"
echo "  railway run python manage.py seed_initial_data"
echo "  railway run python manage.py createsuperuser"
echo ""
echo "PASO 7: Conectar dominio personalizado"
echo "  railway domain"
echo "  # Luego en Cloudflare DNS: CNAME tudominio.com → tu-app.railway.app"
echo ""
echo "============================================"
echo "  Costo estimado: ~\$18-25/mes"
echo "============================================"
