# Generated by Django 4.2.29 on 2026-03-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SunatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("send_invoice", "Enviar Comprobante"),
                            ("consult_status", "Consultar Estado"),
                            ("void", "Comunicación de Baja"),
                            ("consult_ruc", "Consultar RUC"),
                            ("exchange_rate", "Tipo de Cambio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=20)),
                ("document_number", models.CharField(blank=True, max_length=50)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("response_code", models.CharField(blank=True, max_length=10)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log SUNAT",
                "verbose_name_plural": "Logs SUNAT",
                "ordering": ["-created_at"],
            },
        ),
    ]
