# Generated by Django 5.2.12 on 2026-03-07 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "printer_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Impresora"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_registers",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja Registradora",
                "verbose_name_plural": "Cajas Registradoras",
            },
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierta"), ("closed", "Cerrada")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto de Apertura",
                    ),
                ),
                (
                    "closing_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto de Cierre",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Esperado",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Ventas",
                    ),
                ),
                (
                    "total_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Efectivo",
                    ),
                ),
                (
                    "total_card",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Tarjeta",
                    ),
                ),
                (
                    "total_transfer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Transferencia",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Apertura"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cierre"),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="pos.cashregister",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Caja",
                "verbose_name_plural": "Sesiones de Caja",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="POSSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("boleta", "Boleta de Venta"),
                            ("factura", "Factura"),
                            ("nota_venta", "Nota de Venta"),
                            ("ticket", "Ticket"),
                        ],
                        default="boleta",
                        max_length=20,
                    ),
                ),
                ("series", models.CharField(max_length=10, verbose_name="Serie")),
                (
                    "correlative",
                    models.CharField(max_length=20, verbose_name="Correlativo"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("card", "Tarjeta"),
                            ("transfer", "Transferencia"),
                            ("yape", "Yape"),
                            ("plin", "Plin"),
                            ("credit", "Crédito"),
                            ("mixed", "Mixto"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Recibido",
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Vuelto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completada"),
                            ("cancelled", "Anulada"),
                            ("refunded", "Devuelta"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "sunat_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Estado SUNAT"
                    ),
                ),
                ("sunat_response", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_sales",
                        to="crm.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="pos.cashsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta POS",
                "verbose_name_plural": "Ventas POS",
                "ordering": ["-created_at"],
                "unique_together": {("series", "correlative", "doc_type")},
            },
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("card", "Tarjeta"),
                            ("transfer", "Transferencia"),
                            ("yape", "Yape"),
                            ("plin", "Plin"),
                            ("credit", "Crédito"),
                            ("mixed", "Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="pos.possale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pago",
                "verbose_name_plural": "Detalles de Pago",
            },
        ),
        migrations.CreateModel(
            name="POSSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="IGV"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sale_items",
                        to="logistics.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.possale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Venta",
                "verbose_name_plural": "Ítems de Venta",
            },
        ),
    ]
