# Generated by Django 5.2.12 on 2026-03-07 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="N8nIncomingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_customer", "Crear Cliente"),
                            ("update_customer", "Actualizar Cliente"),
                            ("create_product", "Crear Producto"),
                            ("update_stock", "Actualizar Stock"),
                            ("create_invoice", "Crear Comprobante"),
                            ("create_sale", "Crear Venta"),
                            ("send_to_sunat", "Enviar a SUNAT"),
                            ("update_opportunity", "Actualizar Oportunidad"),
                            ("sync_exchange_rate", "Sincronizar Tipo Cambio"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="n8n", max_length=100, verbose_name="Origen"
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "n8n_execution_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="n8n Execution ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Acción Entrante n8n",
                "verbose_name_plural": "Acciones Entrantes n8n",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="N8nWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sale.completed", "Venta Completada"),
                            ("sale.cancelled", "Venta Anulada"),
                            ("session.opened", "Caja Abierta"),
                            ("session.closed", "Caja Cerrada"),
                            ("customer.created", "Cliente Creado"),
                            ("customer.updated", "Cliente Actualizado"),
                            ("opportunity.created", "Oportunidad Creada"),
                            ("opportunity.won", "Oportunidad Ganada"),
                            ("opportunity.lost", "Oportunidad Perdida"),
                            ("interaction.created", "Interacción Registrada"),
                            ("stock.low", "Stock Bajo"),
                            ("stock.movement", "Movimiento de Stock"),
                            ("purchase.created", "Orden de Compra Creada"),
                            ("purchase.received", "Orden de Compra Recibida"),
                            ("product.created", "Producto Creado"),
                            ("invoice.created", "Comprobante Creado"),
                            ("invoice.sunat_accepted", "Comprobante Aceptado SUNAT"),
                            ("invoice.sunat_rejected", "Comprobante Rechazado SUNAT"),
                            ("payment.received", "Pago Recibido"),
                            ("payment.overdue", "Pago Vencido"),
                            ("system.daily_summary", "Resumen Diario"),
                            ("system.backup", "Backup Completado"),
                        ],
                        max_length=50,
                        verbose_name="Evento",
                    ),
                ),
                ("webhook_url", models.URLField(verbose_name="URL del Webhook n8n")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Para verificar autenticidad del webhook",
                        max_length=100,
                        verbose_name="Clave Secreta",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Headers adicionales"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=3, verbose_name="Reintentos"),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Timeout (seg)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook n8n",
                "verbose_name_plural": "Webhooks n8n",
                "ordering": ["event_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="N8nEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("retrying", "Reintentando"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="n8n_integration.n8nwebhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Evento n8n",
                "verbose_name_plural": "Logs de Eventos n8n",
                "ordering": ["-created_at"],
            },
        ),
    ]
